name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 15.9.0
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 15.9.0
      - run: yarn run build
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 15.9.0
      - run: yarn run lint
